// import './css/style.css'

import { Inter } from 'next/font/google'

import Header from '@/components/ui/header'
import Banner from '@/components/banner'

// import { ApolloWrapper } from "@/lib/apollo-wrapper";

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
    display: 'swap'
})

// export const metadata = {
//     title: 'MyChat app',
//     description: 'Generated by create next app',
// }

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        // <html lang="en">
        <div className={`${inter} font-inter antialiased bg-white text-gray-900 tracking-tight`}>
            <div className="Simpleflex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
                <Header />

                {children}

                {/* <Banner /> */}
            </div>
        </div>
        // </html>
    )
}
